### ISSUE TITLE
Publish failed

### ISSUE THREAD

**Issue by AlphaGaming7780** [GreenTF/upload-thunderstore-package#14]
The publishing failed.

I was in v3 the first time and switch to v3.1 when it failed the first time, but failed again in v3.1.
I post the log and the workflow file under the log.

```##[debug]Starting: Set up job
Current runner version: '[2](https://github.com/AlphaGaming7780/Titanfall-Legends/actions/runs/4159039031/jobs/7194728825#step:1:2).[3](https://github.com/AlphaGaming7780/Titanfall-Legends/actions/runs/4159039031/jobs/7194728825#step:1:3)01.1'
Operating System
Runner Image
Runner Image Provisioner
GITHUB_TOKEN Permissions
Secret source: Actions
##[debug]Primary repository: AlphaGaming[7](https://github.com/AlphaGaming7780/Titanfall-Legends/actions/runs/4159039031/jobs/7194728825#step:1:8)780/Titanfall-Legends
Prepare workflow directory
##[debug]Creating pipeline directory: '/home/runner/work/Titanfall-Legends'
##[debug]Creating workspace directory: '/home/runner/work/Titanfall-Legends/Titanfall-Legends'
##[debug]Update context data
##[debug]Evaluating job-level environment variables
##[debug]Evaluating: github.event.repository.name
##[debug]Evaluating Index:
##[debug]..Evaluating Index:
##[debug]....Evaluating Index:
##[debug]......Evaluating github:
##[debug]......=> Object
##[debug]......Evaluating String:
##[debug]......=> 'event'
##[debug]....=> Object
##[debug]....Evaluating String:
##[debug]....=> 'repository'
##[debug]..=> Object
##[debug]..Evaluating String:
##[debug]..=> 'name'
##[debug]=> 'Titanfall-Legends'
##[debug]Result: 'Titanfall-Legends'
##[debug]Evaluating job container
##[debug]Evaluating job service containers
##[debug]Evaluating job defaults
Prepare all required actions
Getting action download info
Download action repository 'actions/checkout@v3' (SHA:ac593985615ec2ede58e132d2e21d2b1cbd6[12](https://github.com/AlphaGaming7780/Titanfall-Legends/actions/runs/4159039031/jobs/7194728825#step:1:14)7c)
##[debug]Download 'https://api.github.com/repos/actions/checkout/tarball/ac593985615ec2ede58e132d2e21d2b1cbd6127c' to '/home/runner/work/_actions/_temp_c0ea8ef7-fe6b-4371-a2ed-59a95a51b3af/adf87bcd-4d3e-4d82-a[20](https://github.com/AlphaGaming7780/Titanfall-Legends/actions/runs/4159039031/jobs/7194728825#step:1:24)2-736862039b1c.tar.gz'
##[debug]Unwrap 'actions-checkout-ac59398' to '/home/runner/work/_actions/actions/checkout/v3'
##[debug]Archive '/home/runner/work/_actions/_temp_c0ea8ef7-fe6b-4371-a2ed-59a95a51b3af/adf87bcd-4d3e-4d82-a202-736862039b1c.tar.gz' has been unzipped into '/home/runner/work/_actions/actions/checkout/v3'.
Download action repository 'GreenTF/upload-thunderstore-package@v3' (SHA:7688a3c957df0830f42a172e8f388778a49539b1)
##[debug]Download 'https://api.github.com/repos/GreenTF/upload-thunderstore-package/tarball/7688a3c957df0830f42a172e8f388778a49539b1' to '/home/runner/work/_actions/_temp_7e9c290a-3f28-45[23](https://github.com/AlphaGaming7780/Titanfall-Legends/actions/runs/4159039031/jobs/7194728825#step:1:27)-afbd-20b92bbeac6e/3178db3b-d804-497d-9932-f6be6d923891.tar.gz'
##[debug]Unwrap 'GreenTF-upload-thunderstore-package-7688a3c' to '/home/runner/work/_actions/GreenTF/upload-thunderstore-package/v3'
##[debug]Archive '/home/runner/work/_actions/_temp_7e9c290a-3f[28](https://github.com/AlphaGaming7780/Titanfall-Legends/actions/runs/4159039031/jobs/7194728825#step:1:32)-4523-afbd-20b92bbeac6e/[31](https://github.com/AlphaGaming7780/Titanfall-Legends/actions/runs/4159039031/jobs/7194728825#step:1:35)78db3b-d804-497d-99[32](https://github.com/AlphaGaming7780/Titanfall-Legends/actions/runs/4159039031/jobs/7194728825#step:1:36)-f6be6d92[38](https://github.com/AlphaGaming7780/Titanfall-Legends/actions/runs/4159039031/jobs/7194728825#step:1:42)91.tar.gz' has been unzipped into '/home/runner/work/_actions/GreenTF/upload-thunderstore-package/v3'.
##[debug]action.yml for action: '/home/runner/work/_actions/actions/checkout/v3/action.yml'.
##[debug]action.yml for action: '/home/runner/work/_actions/GreenTF/upload-thunderstore-package/v3/action.yml'.
Error: 'ghcr.io/greentf/utp:latest' should be either '[path]/Dockerfile' or 'docker://image[:tag]'.
##[debug]System.NotSupportedException: 'ghcr.io/greentf/utp:latest' should be either '[path]/Dockerfile' or 'docker://image[:tag]'.
##[debug]   at GitHub.Runner.Worker.ActionManager.PrepareRepositoryActionAsync(IExecutionContext executionContext, ActionStep repositoryAction)
##[debug]   at GitHub.Runner.Worker.ActionManager.PrepareActionsRecursiveAsync(IExecutionContext executionContext, PrepareActionsState state, IEnumerable`1 actions, Int32 depth, Guid parentStepId)
##[debug]   at GitHub.Runner.Worker.ActionManager.PrepareActionsAsync(IExecutionContext executionContext, IEnumerable`1 steps, Guid rootStepId)
##[debug]   at GitHub.Runner.Worker.JobExtension.InitializeJob(IExecutionContext jobContext, AgentJobRequestMessage message)
##[debug]Finishing: Set up job
```

Workflow :

```
name: Publish package

on:
  release:
    types: [published] # run when a new release is published
    
env:
  name: ${{github.event.repository.name}} # Edit this if the package name differs from the repo name

jobs:
  verify:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: Get clean version
        run: |
          echo cleanVersion=$(echo ${{github.ref_name}} | sed s/v//g) >> $GITHUB_ENV
      - name: Check that version matches
        run: |
          if [[ "$(grep -Po "\d+\.\d+\.\d+" $(find ./ -name mod.json))" != "${{ env.cleanVersion }}" ]]; then
            echo "::debug::${{env.cleanVersion}}"
            echo "::debug::$(cat $(find ./ -name mod.json ))"
            echo "::error::Version in mod.json does not match tag version"
            exit 1
          fi
  publish:
    runs-on: ubuntu-latest
    needs: verify
    steps:
      - uses: actions/checkout@v3
      - name: Upload Thunderstore Package
        uses: GreenTF/upload-thunderstore-package@v3.1
        with:
          community: northstar
          # Name of the team to publish the mod under
          # This should be modified if your github username is different than your team name on Thunderstore
          namespace: Titanfall_Legends # <------ DOUBLE CHECK THIS
          # Name of the package
          name: ${{ env.name }} # This can be modified if the package name differs from the repo name
          # Package version to publish
          version: ${{ github.ref_name }} # This is the tag that was created in the release
          # Description of the mod
          description: Add a Battle Royale gamemode to Titanfall 2. # <----------- UPDATE THIS
          # Thunderstore API token
          token: ${{ secrets.TS_KEY }} 
          # Directory to wrap the contents of the repo in
          wrap: mods/${{ github.repository_owner }}.${{ env.name }} # This will wrap your Author.ModName folder in a mods/ folder before publishing
          #deps: "northstar-Northstar@1.9.3" # <------------- Uncomment this line to add dependencies to your mod, each sparated by a space
          categories: "Mods, Client-side, Server-side"  # <----------------------------- Add more categories as needed, separated by spaces```

**Comment by AlphaGaming7780** [comment]
Well, don't know why but every time I publish they use the v3 instead of the v3.1, they don't care of the workflow file.

**Comment by AlphaGaming7780** [comment]
Okay, good, I manage to publish it.

**Comment by AlphaGaming7780** [comment]
Well this thing this time :
```
ERROR: Unexpected response from the server while publishing package: Status code: 400 BadRequest {"categories":{"0":["Object not found"],"1":["Object not found"]}} Exiting Newer version 0.1.7 of Thunderstore CLI is available
```

**Comment by AlphaGaming7780** [comment]
My fault, just dumb, my bad
